version: "3.9"
services:
  flask_app:
    build: .
    ports:
      - "${PORT}:5000"  # Map the host PORT (from .env) to container's port 5000
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}  # Pass the PORT variable to the container

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Root password
      MYSQL_DATABASE: ${DB_NAME}  # The database to be created
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql
      - mysql-data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql-data:  # Declare a named volume for MySQL data
